// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dischdrcfmuzdfwvfaif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpc2NoZHJjZm11emRmd3ZmYWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTQ1NzcsImV4cCI6MjA3MjEzMDU3N30.d0yasdRnKbr_AU5GJBg81T3pKqGVXk_s4_cIvyegXdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});